# Generated by Django 4.2.7 on 2023-11-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('crime', 'Crime'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('art', 'Art'), ('children', 'Children')], max_length=50)),
            ],
        ),
    ]
